# Site settings
title: Explore
header-img: "img/autumn2.jpg"
tagline: "探索未来"
description: "路漫漫其修远兮 吾将上下而求索"
baseurl: ""
url: ""
#url: "http://localhost:4000"

# About/contact
owner:
  name: "plor"
  email: 1836899619@qq.com
  bio: ""

# Data
gavatar: http://p1.bpimg.com/567571/9afa2901d3e320ab.jpg
favicon: img/favicon.ico

douban_username: plor
twitter_username: plor
github_username: plor
facebook_username: plor
weibo_username: plor
zhihu_username: plor

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: plor/beijin

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "plor"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : plor
  disqus :
      short_name : plor

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
